### ISSUE TITLE
Setting up AWS

### ISSUE THREAD

**Issue by jacksonisiah** [jacksonisiah/discordbot#4]
Anyone know anything about AWS? And which one would be the correct one for running the bot?

**And anything else I would need to know?

**Comment by tyK0ned** [comment]
Not sure too much about setting up AWS specifically, but I do know all you need is a regular 2016 VM or w/e cause node.js does not need many resources to run, it could run in the background of a pc but the downtime would be immense on a regular pc.

**Comment by tyK0ned** [comment]
Just make sure you’ve got node.js downloaded and whatnot. I think that’s all...

**Comment by jacksonisiah** [comment]
I have all windows iso keys from XP to 10 as well as Server 2003-2016

I don't see the point with going consumer or older server

**Comment by jacksonisiah** [comment]
Most likely going to use 2016 for it

Consumer actually would be a higher security risk and take up more resources

The only reason I would use an older server iso would be for less resource usage

**Comment by tyK0ned** [comment]
Resources will NEVER be an issue, trust. You could probably run 15 bots on one pc on multiple servers and not go over 50%

**Comment by jacksonisiah** [comment]
it depends, those servers are pretty limited but it would definitely run and I don't have any reason not to. gonna consult my friend about helping me set that up this week.

**Comment by tyK0ned** [comment]
Tbh it depends for its purposes... 

For our current purposes, we just need it for this server.

**Comment by tyK0ned** [comment]
AWS Set up
